version: 2
jobs:
  build:
    machine:
      docker_layer_caching: true
    steps:
      - checkout
      - run:
          name: Build Docker Images
          command: |
            set -x
            docker-compose -f docker/compose/circle.yaml build

  test:
    machine:
      docker_layer_caching: true
    steps:
      - checkout
      - run:
          name: Start containers
          command: |
            set -x
            docker-compose -f docker/compose/circle.yaml up -d

      - run:
          name: Wait container is ready
          command: |
            set -x
            sleep 20
      - run:
          name: Verify it's working
          command: |
            set -x
            docker exec -it uea-api bash -c "git pull"
            docker exec -it uea-api bash -c "git checkout ${CIRCLE_BRANCH} && git pull"
            docker exec -it uea-api bash -c "npm install --unsafe-perm --only=dev"
            docker exec -it uea-api bash -c "nyc npm run test-unit"
            docker exec -it uea-api bash -c "nyc report --reporter=lcov"
            docker exec -it uea-api bash -c "codecov -t ${CODECOV_TOKEN}"

  coverage:
    machine:
      docker_layer_caching: true
    steps:
      - checkout
      - run:
          name: Deploy to codecov
          command: |
            set -x
            docker exec -it uea-api bash -c "codecov -t ${CODECOV_TOKEN}"

  deploy:
    machine: true
    steps:
      - add_ssh_keys:
          fingerprints:
            - "a5:94:99:bb:d9:3f:72:4c:52:f1:97:4c:0f:b0:28:b8"
      - run:
          name: Deployment
          command: |
            ssh -oStrictHostKeyChecking=no splab@ocarina.splab.ufcg.edu.br /home/splab/deploy/uea2.sh

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - test:
          requires:
            - build
      - coverage:
          requires:
            - test
      - deploy:
          requires:
            - coverage
          filters:
            branches:
              only: master
