version: 2
jobs:
  config:
    docker:
      - image: circleci/cci-demo-docker-primary:0.0.2
    steps:
      - run:
          name: Install Docker client
          command: |
            set -x
            VER="17.03.0-ce"
            curl -L -o /tmp/docker-$VER.tgz https://get.docker.com/builds/Linux/x86_64/docker-$VER.tgz
            tar -xz -C /tmp -f /tmp/docker-$VER.tgz
            mv /tmp/docker/* /usr/bin
      - run:
          name: Install Docker Compose
          command: |
            set -x
            curl -L https://github.com/docker/compose/releases/download/1.11.2/docker-compose-`uname -s`-`uname -m` > /usr/local/bin/docker-compose
            chmod +x /usr/local/bin/docker-compose
  build:
    docker:
      - image: circleci/cci-demo-docker-primary:0.0.2
    steps:
      - checkout
      - run:
          name: Start container and verify it's working
          command: |
            set -x
            docker-compose -f docker/compose/circle.yaml down
            docker-compose -f docker/compose/circle.yaml up -d --build

      - run:
          name: Wait container is ready
          command: |
            set -x
            sleep 20

  test:
    docker:
      - image: circleci/cci-demo-docker-primary:0.0.2
    steps:
      - checkout
      - run:
          name: Start container and verify it's working
          command: |
            set -x
            docker exec -it uea-api bash -c "git pull"
            docker exec -it uea-api bash -c "git checkout ${CIRCLE_BRANCH} && git pull"
            docker exec -it uea-api bash -c "npm install --unsafe-perm --only=dev"
            docker exec -it uea-api bash -c "nyc npm run test-unit"
            docker exec -it uea-api bash -c "nyc report --reporter=lcov"
            docker exec -it uea-api bash -c "codecov -t ${CODECOV_TOKEN}"

  coverage:
    docker:
      - image: circleci/cci-demo-docker-primary:0.0.2
    steps:
      - checkout
      - run:
          name: Deploy to codecov
          command: |
            set -x
            docker exec -it uea-api bash -c "codecov -t ${CODECOV_TOKEN}"

  deploy:
    docker:
      - image: circleci/cci-demo-docker-primary:0.0.2
    steps:
      - add_ssh_keys:
          fingerprints:
            - "a5:94:99:bb:d9:3f:72:4c:52:f1:97:4c:0f:b0:28:b8"
      - run:
          name: Deployment
          command: |
            ssh -oStrictHostKeyChecking=no splab@ocarina.splab.ufcg.edu.br /home/splab/deploy/uea2.sh

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - config
      - build:
          requires:
            - config
      - test:
          requires:
            - build
      - coverage:
          requires:
            - test
      - deploy:
          requires:
            - coverage
          filters:
            branches:
              only: master
